### ISSUE TITLE
macaroonbakery exposes underlying pymacaroon exceptions

### ISSUE THREAD

**Issue by ricardokirkner** [go-macaroon-bakery/py-macaroon-bakery#19]
When attempting to verify a macaroon slice that contains a third party caveat but no discharge macaroons, the bakery is raising 

MacaroonUnmetCaveatException: Caveat not met. No discharge macaroon found for identifier

Instead, I would expect it to wrap that error in a macaroonbakery.DischargeRequiredError bakery exception.

**Comment by rogpeppe** [comment]
Fixed by #60.
