### ISSUE TITLE
platform.dist is deprecated in Python 3.5 and will be removed in 3.8

### ISSUE THREAD

**Issue by cjwatson** [go-macaroon-bakery/py-macaroon-bakery#74]
I noticed this while building the Debian package of py-macaroon-bakery:

```
setup.py:42: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  distribution = platform.dist()
```

https://docs.python.org/3/library/platform.html#platform.dist says that this will be removed in Python 3.8, so this needs to be fixed soon.  It suggests using the [distro](https://pypi.org/project/distro/) package, but that would be awkward in setup.py.

However, I think testing the distribution is the wrong thing to do here anyway.  The correct test is really "is Python older than 2.7.9?" (which is when [lots of ssl module backports](https://docs.python.org/2/whatsnew/2.7.html#pep-466-network-security-enhancements-for-python-2-7) happened), so the test should just be written as `sys.version_info < (2, 7, 9)`.

**Comment by mhilton** [comment]
@frankban could you take a look at this please?
